insert into t_participant_balance_history (id, participant_id, operation_type, transfer_id, amount, currency, settlement_participant_id, time,  comment,         created_at)
values                                    (-1, 100000000003,   'TRANSFER',     1,           1,      'USD',    100000000001,              now(), 'dummy_comment', now()     ),
                                          (-2, 100000000003,   'TRANSFER',     1,           1,      'RUB',    100000000001,              now(), 'dummy_comment', now()     ),
                                          (-3, 100000000003,   'TRANSFER',     1,           1,      'RUB',    10011,                     now(), 'dummy_comment', now()     ),
                                          (-4, 100000000001,   'TRANSFER',     1,           1,      'RUB',    10011,                     now(), 'dummy_comment', now()     )
;

insert into t_participant_balance (id,                                 participant_id, settlement_participant_id, online_balance, minimum_balance, currency, participant_balance_history_id, created_at, updated_at)
values                            (nextval('seq_participant_balance'), 0,              10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 101,            10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 228,            10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 10003,          10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 10005,          10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 10006,          10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 10009,          10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 10029,          10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 10007,          10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 10010,          10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 10036,          10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 10008,          10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 30001,          10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 30002,          10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 30003,          10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 30004,          10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 30005,          10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 30006,          10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 30007,          10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 30008,          10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 10025,          10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 10225,          10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 10325,          10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 10425,          10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 10525,          10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 10026,          10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 1000011,        10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 10227,          10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 10327,          10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 10427,          10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 10527,          10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 1000021,        10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 1000022,        10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 1000023,        10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 1000052,        10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 1000053,        10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 3005001,        10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 3005002,        10011,                     1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 1000023,        1000023,                   1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 1000021,        1000021,                   1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 1000053,        1000023,                   1,              1,               'RUB',    null,                           now(),      null      ),
                                  (nextval('seq_participant_balance'), 1000022,        1000022,                   1,              1,               'RUB',    null,                           now(),      null      ),
                                  (-2,                                 100000000001,   10011,                     1,              1,               'RUB',    -4,                             now(),      null      ),
                                  (-3,                                 100000000002,   100000000003,              1,              1,               'RUB',    null,                           now(),      null      )
;

